In [3]:
BUFFER = "/nfs/kun1/users/avi/scripted_sim_datasets/june30_Widow250PickPlaceMetaTrainMultiObjectMultiContainer-v0_16K_save_all_noise_0.1_2021-06-30T15-51-55/june30_Widow250PickPlaceMetaTrainMultiObjectMultiContainer-v0_16K_save_all_noise_0.1_2021-06-30T15-51-55_16384.npy"

In [4]:
import numpy as np
import matplotlib
with open(BUFFER, 'rb') as fl:
    data = np.load(fl, allow_pickle=True)

In [33]:
print(data[0]['next_observations'][0]['image'])

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [188 162 130]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[189 164 135]
  [187 164 131]
  [188 167 136]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[179 158 129]
  [179 156 127]
  [178 157 129]
  ...
  [158 134 108]
  [158 135 108]
  [158 134 108]]

 [[176 154 126]
  [176 156 128]
  [176 155 126]
  ...
  [158 135 108]
  [156 130 105]
  [158 135 108]]

 [[176 157 127]
  [175 155 126]
  [173 153 124]
  ...
  [157 133 108]
  [159 134 110]
  [158 135 110]]]


In [8]:
import matplotlib.pyplot as plt
idx = 4000
timestep = 29
plt.imshow(data[idx]['next_observations'][timestep]['image'])
print(data[idx]['env_infos'][timestep]['task_idx'])
print(len(data[100]['actions']))

26
30
